### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by YUSUNRO** [YUSUNRO/Git-Practice#1]
### 만들고자 하는 기능
- Todo생성 기능

### 해당 기능을 구현하기 위해 할 일
1. [ ] entity class 구현
2. [ ] dto class 구현
3. [ ] application.yml 파일 작성

### 예상 작업 시간
- 2h
